### ISSUE TITLE
problem with path containing spaces on Windows

### ISSUE THREAD

**Issue by shadow2560** [koolkdev/wfslib#9] opened 2018-07-03 13:59 UTC
Helo,

I encounter some errors when I try to use the program with path(s) containing spaces (tested on Windows, I don't know if this problem occure on other OS). I've tried:

wfs-extract.exe --input "path with spaces" --output "path with spaces" --otp "path with spaces" --mlc

With this the program complain about otp and seeprom missing.

wfs-extract.exe --input 'path with spaces' --output 'path with spaces' --otp 'path with spaces' --mlc

This time the program tells that it can't open otp file.

wfs-extract.exe --input path with spaces --output path with spaces --otp path with spaces --mlc

Same problem as the command before, the program can't open otp file.

wfs-extract.exe --input "path_without_spaces" --output "path_without_spaces" --otp "path_without_spaces" --mlc

Same errors than the first command I have described.

wfs-extract.exe --input path_without_spaces --output path_without_spaces --otp path_without_spaces --mlc

Obviously work.

I want to integrate this in a script but the path could be different from one user to an other, that's why I want to minimize errors of this type.

Thanks.

**Comment by koolkdev** [comment] 2022-01-05 20:05
Hi, sorry for the delayed response. I am closing this issue as I can't reproduce this issue. When you arguments with spaces inside quotes the shell environment (cmd for example in windows) responsible for passing it as one argument and not to split it. If it is split somehow it is a problem in your environment. did you run it with cmd.exe?

**Closed by koolkdev** 2022-01-05 20:05 UTC
